import DefaultLayout from '@/components/layouts/defaultLayout/defaultLayout'
import type { Metadata } from 'next'
import '@/styles/variables.scss'
import '@/styles/global.scss'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<DefaultLayout>
					{children}
				</DefaultLayout>
			</body>
		</html>
	)
}
